yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied_view'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}

<div class="container">
    <h1>Привет, меня зовут Александр</h1>
    <p>Мое резюме можно посмотреть <a href="">тут</a></p>
    <hr>
    <p>Это мой первый проект на Django он размещен на <a href="https://github.com/SashaAhrom">Github</a></p>
    <br>
    <p>Программирование мне нравилось с института но переучится и сменить работу я решился только в 2020 году. До этого я работая инженером-конструкторам</p>
    {% load static %}
        <a class="navbar-brand" href="{% url 'about:tech' %}" title="Технологии">
        <img src={% static "img/about/tech.jpeg" %} width="100" height="100" class="d-inline-block align-top" alt=""></a>
         </a>
    </div>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="row">
  <h1>Приобретенные навыки.</h1>

  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
        <li class="list-group-item">
        Git
      </li>
    </ul>
  </aside>

  <article class="col-12 col-md-9">
      <p><a href="https://www.python.org/">Python документация</a></p>
      <p><a href="https://www.python.org/">Django документация</a></p>
      <p><a href="https://git-scm.com/book/ru/v2">Git документация</a></p>

  </article>

</div>
{% endblock %} 