yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('create/', views.post_create, name='post_create'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied_view'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """Community model."""
    title = models.CharField('title', max_length=200)
    slug = models.SlugField('group name', unique=True)
    description = models.TextField('description')

    class Meta:
        verbose_name = 'community'
        db_table = 'community of Tolstoy lovers'

    def __str__(self):
        return self.title


class Post(models.Model):
    """Model for records, field group is linked by model
    Group and author is linked by User."""
    text = models.TextField('article', help_text='Введите текст поста')
    pub_date = models.DateTimeField('year of writing', auto_now_add=True)
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        verbose_name='group name',
        related_name='community',
        help_text='Выберите группу',
        blank=True,
        null=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='author',
        related_name='author_posts')
    image = models.ImageField(
        'beautiful image',
        upload_to='posts/',
        blank=True,
        help_text='Загрузить картинку'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'notes of famous people'
        db_table = 'all post'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    """Add commets to post."""
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='post name',
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='author name',
        related_name='author_comments')
    text = models.TextField('coment', help_text='Введите текст коментария')
    created = models.DateTimeField('time of writing', auto_now_add=True)

    class Meta:
        verbose_name = 'comments'
        db_table = 'users comments'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    """Subscribe to the author."""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='name',
        related_name='follower')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='post author',
        related_name='following')

    class Meta:
        verbose_name = 'subscriptions'
        db_table = 'author subscriptions'
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='unique_subscription'),
            models.CheckConstraint(check=~models.Q(author=models.F('user')),
                                   name='not_subscription_by_myself'),
        ]

    def __str__(self):
        return f'{self.user} subscribed to {self.author}'

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def index(request):
    """Passes the last ten Post model objects and title."""
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.PAGINATOR_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Passes the last ten Post model objects
    filtered by group field and title."""
    group = get_object_or_404(Group, slug=slug)
    post_list = group.community.all()
    paginator = Paginator(post_list, settings.PAGINATOR_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
        'title': group.title
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """All posts author."""
    author = get_object_or_404(User, username=username)
    post_list = author.author_posts.all()
    paginator = Paginator(post_list, settings.PAGINATOR_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title = f'Профайл пользователя {author}'
    following = author.following.all()
    context = {
        'post_list': post_list,
        'page_obj': page_obj,
        'author': author,
        'title': title,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Post details."""
    post = get_object_or_404(Post, pk=post_id)
    post_count = Post.objects.filter(author=post.author)
    post_comments = post.comments.all()
    title = f'Пост {post.text[:30]}'
    form = CommentForm()
    context = {
        'post': post,
        'title': title,
        'post_count': post_count,
        'form': form,
        'comments': post_comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """Create post."""
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author_id = request.user.id
            post.save()
            return redirect(f'/profile/{request.user.username}/')
        return render(request, 'posts/create_post.html', {'form': form})
    context = {
        'form': form
    }
    return render(request, 'posts/create_post.html', context)


def post_edit(request, post_id):
    """Post edit."""
    post = get_object_or_404(Post, pk=post_id)
    if post.author.id != request.user.id:
        return redirect(f'/posts/{post.pk}/')
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(f'/posts/{post.pk}/')
    context = {
        'form': form,
        'post': post
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """All author subscriptions."""
    user = request.user
    author_follow = user.follower.values_list('author', flat=True)
    post_list = Post.objects.filter(author__in=author_follow)
    paginator = Paginator(post_list, settings.PAGINATOR_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Add subscription."""
    user = request.user
    author = get_object_or_404(User, username=username)
    try:
        Follow.objects.create(
            user=user,
            author=author
        ).save()
    except IntegrityError:
        return redirect('posts:follow_index')
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    """Delete subscription."""
    author = get_object_or_404(User, username=username)
    get_object_or_404(Follow, user=request.user, author=author)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}Новый пост{% endblock %}
{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        {% if post %}
                            Редактировать запись
                        {% else %}
                            Добавить запись
                        {% endif %}
                    </div>
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}


                    <div class="card-body">
                        <form method="post"
                              action="{% if post %}
                                        {% url 'posts:post_edit' post_id=post.id %}
                                      {% else %}
                                        {% url 'posts:post_create' %}
                                      {% endif %}"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            {% load user_filters %}
                            {% for field in form %}
                            <div class="form-group row my-3 p-3">
                                <label for="id_text">
                                    {{ field.label }}
                                    <span class="required text-danger">*</span>
                                </label>
                                {{ field|addclass:"form-control" }}
                                <small id="id_text-help" class="form-text text-muted">
                                    {{ field.help_text }}
                                </small>
                            </div>

                            {% endfor %}
                                <div class="d-flex justify-content-end">
                                    <button type="submit" class="btn btn-primary">
                                        {% if post %}
                                            Сохранить
                                        {% else %}
                                            Добавить
                                        {% endif %}
                                    </button>
                                </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}Ваши подписки{% endblock %}
{% block content %}
    <div class="container py-5">
        <h1>Ваши подписки</h1>

            {% include 'posts/includes/switcher.html' %}
            {% for post in page_obj %}
                <ul>
                    <li>Автор: {{ post.author.get_full_name }} <a href="{% url 'posts:profile' post.author.username %}">все
                        посты пользователя</a></li>
                    <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
                </ul>
                {% include "posts/includes/thumbnail.html" %}
                <p>{{ post.text }}</p>
                <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
                <br>
                {% if post.group %}
                    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                {% endif %}
                {% if not forloop.last %}
                    <hr/>
                {% endif %} {% endfor %}

            </div>

            {% include "posts/includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %} {% block title %} {{ title }} {% endblock %}
{% block content %}
    <div class="container py-5">
        <h1>{{ group.title }}</h1>
        <p>{{ group.description }}</p>

        {% for post in page_obj %}
            <ul>
                <li>Автор: {{ post.author.get_full_name }}
                    <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
                </li>
                <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
            </ul>
            {% include "posts/includes/thumbnail.html" %}
            <p>{{ post.text }}</p>
            <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a><br>
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% if not forloop.last %}
                <hr/>
            {% endif %} {% endfor %}
    </div>
    {% include "posts/includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
    <div class="container py-5">
        <h1>Последние обновления на сайте</h1>
        {% load cache %}
        {% cache 20 index_page %}
            {% include 'posts/includes/switcher.html' %}
            {% for post in page_obj %}
                <ul>
                    <li>Автор: {{ post.author.get_full_name }} <a href="{% url 'posts:profile' post.author.username %}">все
                        посты пользователя</a></li>
                    <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
                </ul>
                {% include "posts/includes/thumbnail.html" %}
                <p>{{ post.text }}</p>
                <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
                <br>
                {% if post.group %}
                    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                {% endif %}
                {% if not forloop.last %}
                    <hr/>
                {% endif %} {% endfor %}

            </div>
            {% endcache %}
            {% include "posts/includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}{{ title }} {% endblock %}
{% block content %}
    {% load user_filters %}
    <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
                {% if post.group %}
                    <li class="list-group-item">
                        Группа: {{ post.group }}
                        <a href="{% url 'posts:group_list' post.group.slug %}">
                            все записи группы
                        </a>
                    </li>
                    <li class="list-group-item">
                        Автор: {{ post.author.username }}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Всего постов автора: <span>{{ post_count|length }}</span>
                    </li>
                {% endif %}
                <li class="list-group-item">
                    <a href="{% url 'posts:profile' post.author.username %}">
                        все посты пользователя
                    </a>
                </li>
            </ul>
        </aside>
        <article class="col-12 col-md-9">
            {% include "posts/includes/thumbnail.html" %}
            <p>
                {{ post.text }}
            </p>
            {% if user.get_username == post.author.username %}
                <a href="{% url 'posts:post_edit' post.id %}">редактировать запись</a>
            {% endif %}
        </article>
    </div>
    {% if user.is_authenticated %}
        <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' post.id %}">
                    {% csrf_token %}
                    <div class="form-group mb-2">
                        {{ form.text|addclass:"form-control" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
            </div>
        </div>
    {% endif %}

    {% for comment in comments %}
        <div class="media mb-4">
            <div class="media-body">
                <h5 class="mt-0">
                    <a href="{% url 'posts:profile' comment.author.username %}">
                        {{ comment.author.username }}
                    </a>
                </h5>
                <p>
                    {{ comment.text }}
                </p>
            </div>
        </div>
    {% endfor %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}{{ title }} {% endblock %}
{% block content %}
    <div class="container py-5 mb-5">
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>

        <h3>Всего постов: {{ post_list|length }} </h3>
            {% if following|length %}
                <a
                        class="btn btn-lg btn-light"
                        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
                >
                    Отписаться
                </a>
            {% else %}
                <a
                        class="btn btn-lg btn-primary"
                        href="{% url 'posts:profile_follow' author.username %}" role="button"
                >
                    Подписаться
                </a>
            {% endif %}

        {% for post in page_obj %}
            <article>
                <ul>
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </ul>
                {% include "posts/includes/thumbnail.html" %}
                <p>
                    {{ post.text }}
                </p>
                <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
            </article>
            {% if post.group %}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}
                <hr>
            {% endif %} {% endfor %}
        {% include "posts/includes/paginator.html" %}
    </div>

{% endblock %}